# MUPAI - Configuración de Secrets para Streamlit
# ================================================
# 
# Este archivo muestra cómo configurar las credenciales SMTP de forma segura
# para el sistema de cuestionarios MUPAI.
#
# INSTRUCCIONES:
# 1. Copia este archivo a .streamlit/secrets.toml en tu proyecto
# 2. Reemplaza los valores de ejemplo con tus credenciales reales
# 3. Asegúrate de que .streamlit/secrets.toml esté en tu .gitignore
# 4. En producción, configura estos secrets en tu plataforma de deployment

# Configuración SMTP para Zoho Mail
smtp_server = "smtp.zoho.com"
smtp_port = 587

# Credenciales de email (REEMPLAZA CON TUS CREDENCIALES REALES)
email_usuario = "tu_email@tudominio.com"
email_password = "tu_contraseña_aqui"

# Email de destino para recibir los cuestionarios
email_destino = "administracion@muscleupgym.fitness"

# Configuración adicional (opcional)
email_nombre_remitente = "Sistema MUPAI"
email_asunto_prefijo = "MUPAI"

# IMPORTANTE: 
# - Nunca commits este archivo con credenciales reales
# - Usa contraseñas de aplicación específicas en lugar de tu contraseña principal
# - Considera usar variables de entorno en producción
# - Habilita la autenticación de dos factores en tu cuenta de email